name: CI

on:
  push:
    branches:
      - main
      - master
      - next
      - v*
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: fastify/workflows/.github/workflows/plugins-ci-redis.yml@main
    with:
      license-check: true
      lint: true
