name: Publish Package

on:
  workflow_dispatch:
    inputs:
      Version:
        description: "Mention Version of your Release"
        required: True
        type: string

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  Publish:
    name: Publish [${{ github.event.inputs.Version }}]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "18.16.0"
      
      - name: Login to Github Packages
        env: 
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${TOKEN}" >> ~/.npmrc

      - name: Install Dependencies
        run: |
          npm install

      - name: Bump Package Version & Replace Package
        env:
          VERSION: ${{ github.event.inputs.Version }}
        run: |
          envsubst < ./package.json > ./package-new.json
          rm package.json
          mv package-new.json package.json
      
      - name: Build Package
        run: |
          npm run test:typescript

      - name: Publish Package
        run: |
          npm publish 
      - name: Create Tags
        uses: rickstaa/action-create-tag@v1.6.1
        with:
          tag: v${{ github.event.inputs.Version }}
          force_push_tag: true